"""EL Core - LLM-native interview agent with knowledge graph integration."""

from el_core.agent import ELAgent
from el_core.schemas import (
    ConsistencyIssue,
    ConsistencyIssueKind,
    ConsistencyIssueStatus,
    ConversationTurn,
    DateType,
    DocumentChunk,
    Insight,
    KnowledgeGraphData,
    KnowledgeGraphEdge,
    KnowledgeGraphNode,
    Message,
    PendingQuestion,
    QuestionKind,
    QuestionStatus,
    Session,
    Tag,
    TaggedItem,
    TaggedItemType,
    TagMergeRequest,
    TagMergeResult,
    TagStats,
    TagSuggestion,
    TagSuggestionResult,
)

__version__ = "2.0.0"
__all__ = [
    "ELAgent",
    "ConsistencyIssue",
    "ConsistencyIssueKind",
    "ConsistencyIssueStatus",
    "ConversationTurn",
    "DateType",
    "DocumentChunk",
    "Insight",
    "KnowledgeGraphData",
    "KnowledgeGraphEdge",
    "KnowledgeGraphNode",
    "Message",
    "PendingQuestion",
    "QuestionKind",
    "QuestionStatus",
    "Session",
    "Tag",
    "TaggedItem",
    "TaggedItemType",
    "TagMergeRequest",
    "TagMergeResult",
    "TagStats",
    "TagSuggestion",
    "TagSuggestionResult",
]
