name: Calibrate Evaluator Weights

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday 03:00 UTC
  workflow_dispatch: {}

jobs:
  calibrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calibration
        run: |
          python scripts/calibrate_evaluator.py --labels reports/labels.jsonl --out config/weights/weights.json --min-samples 50

      - name: Commit weights if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add config/weights/weights.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update calibrated evaluator weights"
            git push
          else
            echo "No changes to commit"
          fi

